#!/bin/bash -ex

let day=(24)
let week=(7*24)
let month=(30*24)

files=$(ls *.gnuplot | cut -f1 -d. | sort | uniq)

function size_files() {
    label=$1
    lines=$2
    for i in $files; do
        ./csvsize input/$i.csv $lines > input/$i-$label.csv
    done
}

function gen() {
    name=$1
    dur=$2
    sed -e "s/DUR/$dur/" < $name.gnuplot > /tmp/$$.gnuplot
    gnuplot /tmp/$$.gnuplot > output/$name-$dur.svg
    rm /tmp/$$.gnuplot
}

size_files month $month
for i in $files; do
    gen $i month
done
