#!/bin/bash -ex

files="ba ewl lvs ewl-export ewl-na1-export ewl-na2-export lvs-export"

function gen() {
    name=$1
    lines=$2
    /Applications/Inkscape.app/Contents/Resources/bin/inkscape \
        --without-gui --export-png $(pwd)/output/store-$name.png \
        --export-background white $(pwd)/output/store-$name.svg
}

for i in $files; do
    gen $i-week $week
done
