#!/bin/bash -ex

function gen() {
    type=$1
    sed -e "s/TYPE/$type/g" < exp-requests.gnuplot > /tmp/$$.gnuplot
    gnuplot /tmp/$$.gnuplot > output/exp-requests-$type.svg
    rm /tmp/$$.gnuplot
}

gen count
gen seqs

gnuplot exp-done.gnuplot > output/exp-done.svg
