#!/bin/bash -ex

files="completed requested"

function gen() {
    name=$1
    dur=$2
    /Applications/Inkscape.app/Contents/Resources/bin/inkscape \
        --without-gui --export-png $(pwd)/output/$name-$dur.png \
        --export-background white $(pwd)/output/$name-$dur.svg
}

for i in $files; do
    gen $i week
    gen $i month
    gen $i quarter
done

types="count seqs"

function gen() {
    type=$1
    /Applications/Inkscape.app/Contents/Resources/bin/inkscape \
        --without-gui --export-png $(pwd)/output/exp-requests-$type.png \
        --export-background white $(pwd)/output/exp-requests-$type.svg
}

gen count
gen seqs
